list: $/alex/obrazovanie/models/obrazovanie/columns.yaml
modelClass: Alex\Obrazovanie\Models\Obrazovanie
title: Obrazovanie
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/obrazovanie/obrazovanie/update/:id'
