list: $/alex/zakupki/models/alex_zakupki_/columns.yaml
modelClass: Alex\Zakupki\Models\Alex_zakupki_
title: Zakups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/zakupki/zakups/update/:id'
