list: $/alex/resppat/models/resppat/columns.yaml
modelClass: Alex\Resppat\Models\RespPat
title: RespPat
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/resppat/resppat/update/:id'
