list: $/alex/pacientsupport/models/pacientsupport/columns.yaml
modelClass: Alex\Pacientsupport\Models\PacientSupport
title: PacientSupport
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/pacientsupport/pacientsupport/update/:id'
