list: $/alex/missia/models/missia/columns.yaml
modelClass: Alex\Missia\Models\Missia
title: Missia
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/missia/missia/update/:id'
