list: $/alex/slider/models/slider/columns.yaml
modelClass: Alex\Slider\Models\Slider
title: Slider
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/slider/slider/update/:id'
