list: $/alex/zapros/models/zapros/columns.yaml
modelClass: Alex\Zapros\Models\Zapros
title: Zapros
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/zapros/zapros/update/:id'
