list: $/alex/pacientgosp/models/pacientgosp/columns.yaml
modelClass: Alex\Pacientgosp\Models\PacientGosp
title: PacientGos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/pacientgosp/pacientgos/update/:id'
