list: $/alex/blogd/models/blogd/columns.yaml
modelClass: Alex\Blogd\Models\BlogD
title: BlogD
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/blogd/blogd/update/:id'
