list: $/alex/extratrav/models/extratrav/columns.yaml
modelClass: Alex\Extratrav\Models\ExtraTrav
title: ExtraTrav
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/extratrav/extratrav/update/:id'
