list: $/alex/ms/models/ms/columns.yaml
modelClass: Alex\Ms\Models\MS
title: MS
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/ms/ms/update/:id'
