list: $/alex/struktura/models/struktura/columns.yaml
modelClass: Alex\Struktura\Models\Struktura
title: Struktura
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/struktura/struktura/update/:id'
