list: $/alex/nauka/models/nauka/columns.yaml
modelClass: Alex\Nauka\Models\Nauka
title: Nauka
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/nauka/nauka/update/:id'
