title: Klinika
modelClass: Alex\Klinika\Models\Klinika
list: $/alex/klinika/models/klinika/columns.yaml
recordUrl: 'alex/klinika/klinika/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
