list: $/alex/corp/models/corp/columns.yaml
modelClass: Alex\Corp\Models\Corp
title: Corp
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/corp/corp/update/:id'
