list: $/alex/metodic/models/metodic/columns.yaml
modelClass: Alex\Metodic\Models\Metodic
title: Metodic
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/metodic/metodic/update/:id'
