list: $/alex/respsporttravm/models/respsporttravm/columns.yaml
modelClass: Alex\Respsporttravm\Models\RespSportTravm
title: RespSportTravm
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/respsporttravm/respsporttravm/update/:id'
