list: $/alex/pacientgraf/models/pacientgraf/columns.yaml
modelClass: Alex\Pacientgraf\Models\PacientGraf
title: PacientGraf
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/pacientgraf/pacientgraf/update/:id'
