name: Juranl
modelClass: Alex\Jurnal\Models\Jurnal
form: $/alex/jurnal/models/jurnal/fields.yaml
defaultRedirect: alex/jurnal/juranl
create:
    redirect: 'alex/jurnal/juranl/update/:id'
    redirectClose: alex/jurnal/juranl
update:
    redirect: alex/jurnal/juranl
    redirectClose: alex/jurnal/juranl
preview: {  }
