list: $/alex/boss/models/boss/columns.yaml
modelClass: Alex\Boss\Models\Boss
title: Boss
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/boss/boss/update/:id'
