title: Activity
modelClass: Alex\Activity\Models\Activity
list: $/alex/activity/models/activity/columns.yaml
recordUrl: 'alex/activity/activity/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
